=encoding UTF-8

=head1 НАЗВАНИЕ

perlbook - Информация о книгах по Perl

=head1 ОПИСАНИЕ

Книга Ларри Уолла "Программирование на Perl, 3-е издание" (Camel Book) – наиболее полный справочник, включающий почти все, что есть в Perl. Вы можете заказать эту и другие книги от издательства O'Reilly & Associates, 1-800-998-9938 местный/за границей +1 707 829 0515. Если вы нашли форму заказа O'Reilly, то можете отправить факс на +1 707 829 0104. Также можете совершить он-лайн заказ на сайте L<http://www.oreilly.com/>.

Другие книги по языку Perl различных издательств и авторов Вы можете найти в L<perlfaq2> или на сайте L<http://books.perl.org/>.

Оригинал (Английский): perlbook

=head1 ПЕРЕВОД

Оригинал: L<perlbook>

Он-лайн перевод: L<http://translated.by/you/perlbook/trans/>

=cut
